# **Import Pandas**

In [10]:
import pandas as pd

# **NULL IRIS DATASET**

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
null_iris_df = pd.read_csv('/iris_with_null.csv')
null_iris_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,NaN,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,NaN,5.1,1.8,Iris-virginica

**`describe()`** gives a statistical summary of all numeric columns — count, mean, min, max, std etc. If data has null values, count will be lower than total rows.

In [6]:
null_iris_df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     145.000000    141.000000     141.000000    140.000000
mean    75.500000       5.850345      3.063121       3.751064      1.202857
std     43.445368       0.824042      0.439872       1.788959      0.766562
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.300000      1.300000
75%    112.750000       6.400000      3.400000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

**`info()`** shows column names, data types, and non-null counts. Best way to spot missing values — if non-null count is less than total rows, that column has nulls.

In [7]:
null_iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  145 non-null    float64
 2   SepalWidthCm   141 non-null    float64
 3   PetalLengthCm  141 non-null    float64
 4   PetalWidthCm   140 non-null    float64
 5   Species        145 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

**`isnull().sum()`** counts the total number of null values in each column.

In [8]:
null_iris_df.isnull().sum()

Id                0
SepalLengthCm     5
SepalWidthCm      9
PetalLengthCm     9
PetalWidthCm     10
Species           5
dtype: int64

**`dropna()`** removes all rows that contain at least one null value.
But it's risky so we sould use cleaned_df. so we should use: **cleaned_df = null_iris_df.dropna()**

In [9]:
cleaned_df = null_iris_df.dropna()
cleaned_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica

**`isnull().sum()`** counts the total number of null values in each column after deleting all the empty or null rows

In [10]:
cleaned_df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

**`drop()`** removes a specific column from the DataFrame. `axis=1` means we are targeting a column, not a row.

In [11]:
cleaned_df = null_iris_df.dropna(axis=1)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
143  144            6.8           3.2            5.9           2.3
144  145            6.7           3.3            5.7           2.5
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
148  149            6.2           3.4            5.4           2.3

[114 rows x 5 columns]

**`shape`** returns the total number of rows and columns in the DataFrame as `(rows, columns)`.

In [12]:
cleaned_df.shape

(114, 6)

**Back to NUll Dataset**

In [11]:
null_iris_df = pd.read_csv('/iris_with_null.csv')
null_iris_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,NaN,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,NaN,5.1,1.8,Iris-virginica

**Check Info**

In [12]:
null_iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  145 non-null    float64
 2   SepalWidthCm   141 non-null    float64
 3   PetalLengthCm  141 non-null    float64
 4   PetalWidthCm   140 non-null    float64
 5   Species        145 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

**Check Mean Value of a Column **

In [19]:
null_iris_df['SepalLengthCm'].mean()

np.float64(5.850344827586206)

**`fillna()`** replaces null values with a specified value. For numeric columns, filling with **mean** is the safest option as it does not affect the overall distribution of the data.
but create another variabe is better option

In [20]:
mean_filled_df = null_iris_df.copy()
mean_filled_df['SepalLengthCm'] = mean_filled_df['SepalLengthCm'].fillna(mean_value)
mean_filled_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,NaN,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,NaN,5.1,1.8,Iris-virginica

**To check: **

In [21]:
mean_filled_df['SepalLengthCm'].isnull().sum()

np.int64(0)

**Boolean masking** filters rows based on a condition. Since we filled nulls with mean, we check which rows have exactly the mean value.

In [22]:
mean_filled_df[mean_filled_df['SepalLengthCm'] == mean_value]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
31,32,5.850345,3.4,1.5,0.4,Iris-setosa
42,43,5.850345,NaN,1.3,0.2,Iris-setosa
44,45,5.850345,3.8,1.9,0.4,Iris-setosa
50,51,5.850345,3.2,4.7,1.4,Iris-versicolor
136,137,5.850345,3.4,5.6,2.4,Iris-virginica

**`mode()`** returns the most frequently occurring value in a column. Used for categorical data like Species.

In [23]:
null_iris_df['Species'].mode()

0    Iris-virginica
Name: Species, dtype: object

In [24]:
null_iris_df['Species'].value_counts()

Species
Iris-virginica     50
Iris-setosa        49
Iris-versicolor    46
Name: count, dtype: int64

**`fillna()`** with `mode()[0]` replaces null values in a categorical column with the most frequent value. `mode()[0]` is used because `mode()` returns a Series, so we take the first value.

**Step 1** — Fill up with Mode

**Step 2** — Check those Null row which are replaced by Null

**Here we can see all the rows which repleaced by mean and mode**

In [27]:
mean_filled_df['Species'] = mean_filled_df['Species'].fillna(mode_value)
mean_filled_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,NaN,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,NaN,5.1,1.8,Iris-virginica

In [28]:
mean_filled_df[mean_filled_df['Species'] == mode_value]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
7,8,5.000000,3.4,1.5,0.2,Iris-virginica
59,60,5.200000,2.7,3.9,1.4,Iris-virginica
63,64,6.100000,2.9,4.7,1.4,Iris-virginica
73,74,6.100000,2.8,4.7,1.2,Iris-virginica
99,100,5.700000,2.8,4.1,1.3,Iris-virginica
100,101,6.300000,3.3,6.0,2.5,Iris-virginica
101,102,5.800000,NaN,5.1,1.9,Iris-virginica
102,103,7.100000,3.0,5.9,2.1,Iris-virginica
103,104,6.300000,2.9,5.6,1.8,Iris-virginica
104,105,6.500000,3.0,5.8,2.2,Iris-virginica
105,106,7.600000,3.0,6.6,NaN,Iris-virginica
106,107,4.900000,2.5,4.5,1.7,Iris-virginica
107,108,7.300000,2.9,6.3,NaN,Iris-virginica
108,109,6.700000,2.5,5.8,1.8,Iris-virginica
109,110,7.200000,3.6,6.1,2.5,Iris-virginica
110,111,6.500000,3.2,5.1,2.0,Iris-virginica
111,112,6.400000,2.7,5.3,1.9,Iris-virginica
112,113,6.800000,3.0,5.5,2.1,Iris-virginica
113,114,5.700000,2.5,5.0,2.0,Iris-virginica
114,115,5.800000,2.8,5.1,2.4,Iris-virginica
115,116,6.400000,3.2,5.3,2.3,Iris-virginica
116,117,6.500000,3.0,5.5,1.8,Iris-virginica
117,118,7.700000,3.8,6.7,2.2,Iris-virginica
118,119,7.700000,2.6,6.9,2.3,Iris-virginica
119,120,6.000000,2.2,5.0,1.5,Iris-virginica
120,121,6.900000,3.2,5.7,2.3,Iris-virginica
121,122,5.600000,2.8,4.9,2.0,Iris-virginica
122,123,7.700000,2.8,6.7,2.0,Iris-virginica
123,124,6.300000,2.7,4.9,1.8,Iris-virginica
124,125,6.700000,3.3,5.7,2.1,Iris-virginica
125,126,7.200000,3.2,6.0,1.8,Iris-virginica
126,127,6.200000,2.8,4.8,1.8,Iris-virginica
127,128,6.100000,3.0,4.9,1.8,Iris-virginica
128,129,6.400000,2.8,5.6,2.1,Iris-virginica
129,130,7.200000,3.0,5.8,1.6,Iris-virginica
130,131,7.400000,2.8,6.1,1.9,Iris-virginica
131,132,7.900000,3.8,6.4,2.0,Iris-virginica
132,133,6.400000,2.8,5.6,2.2,Iris-virginica
133,134,6.300000,2.8,5.1,1.5,Iris-virginica
134,135,6.100000,2.6,5.6,1.4,Iris-virginica
135,136,7.700000,3.0,6.1,2.3,Iris-virginica
136,137,5.850345,3.4,5.6,2.4,Iris-virginica
137,138,6.400000,3.1,5.5,1.8,Iris-virginica
138,139,6.000000,3.0,4.8,1.8,Iris-virginica
139,140,6.900000,3.1,5.4,2.1,Iris-virginica
140,141,6.700000,3.1,5.6,2.4,Iris-virginica
141,142,6.900000,3.1,5.1,NaN,Iris-virginica
142,143,5.800000,2.7,5.1,1.9,Iris-virginica
143,144,6.800000,3.2,5.9,2.3,Iris-virginica
144,145,6.700000,3.3,5.7,2.5,Iris-virginica
145,146,6.700000,3.0,5.2,2.3,Iris-virginica
146,147,6.300000,2.5,5.0,1.9,Iris-virginica
147,148,6.500000,NaN,5.2,2.0,Iris-virginica
148,149,6.200000,3.4,5.4,2.3,Iris-virginica
149,150,5.900000,NaN,5.1,1.8,Iris-virginica

**`isnull()`** finds the null positions in the original dataset and saves their index. Then **`loc[]`** uses those saved indexes to display only the rows that were replaced with mode.

In [29]:
null_species_index = null_iris_df[null_iris_df['Species'].isnull()].index
mean_filled_df.loc[null_species_index]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
7,8,5.0,3.4,1.5,0.2,Iris-virginica
59,60,5.2,2.7,3.9,1.4,Iris-virginica
63,64,6.1,2.9,4.7,1.4,Iris-virginica
73,74,6.1,2.8,4.7,1.2,Iris-virginica
99,100,5.7,2.8,4.1,1.3,Iris-virginica

**`pd.DataFrame()`** creates a DataFrame manually. `None` is used to represent missing/null values in Python which Pandas reads as `NaN`.

In [30]:
data = {
    'Name': ['Alice', 'Bob', None, 'David', None],
    'Age': [25, None, 35, None, 28],
    'Score': [85, 90, None, 78, None]
}

df = pd.DataFrame(data)
df

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob   NaN   90.0
2   None  35.0    NaN
3  David   NaN   78.0
4   None  28.0    NaN

**`ffill()`** (forward fill) replaces null values with the **previous row's value**. It fills forward, meaning it takes the last valid value above the null and fills it down.

In [31]:
ffill_df = df.ffill()
ffill_df

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob  25.0   90.0
2    Bob  35.0   90.0
3  David  35.0   78.0
4  David  28.0   78.0

**`bfill()`** (backward fill) replaces null values with the **next row's value**. It fills backward, meaning it takes the next valid value below the null and fills it up.

In [32]:
bfill_df = df.bfill()
bfill_df

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob  35.0   90.0
2  David  35.0   78.0
3  David  28.0   78.0
4   None  28.0    NaN

**`describe()`** helps detect outliers by comparing **min, max** with **mean and std**. If max is much higher or min is much lower than mean, there are likely outliers.

**Step 1** — Statistical summary
**Step 2** — Outlier Detect using IQR method

**IQR (Interquartile Range)** = Q3 - Q1. Any value below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR` is considered an outlier.

In [33]:
df.describe()

             Age      Score
count   3.000000   3.000000
mean   29.333333  84.333333
std     5.131601   6.027714
min    25.000000  78.000000
25%    26.500000  81.500000
50%    28.000000  85.000000
75%    31.500000  87.500000
max    35.000000  90.000000

In [34]:
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)
IQR = Q3 - Q1

outliers = df[(df['Age'] < Q1 - 1.5 * IQR) | (df['Age'] > Q3 + 1.5 * IQR)]
outliers

Empty DataFrame
Columns: [Name, Age, Score]
Index: []